# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.30.5/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.30.5/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/lin/battle_game_2024

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/lin/battle_game_2024

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.30.5/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.30.5/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lin/battle_game_2024/CMakeFiles /Users/lin/battle_game_2024//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lin/battle_game_2024/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named grassland

# Build rule for target.
grassland: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 grassland
.PHONY : grassland

# fast build rule for target.
grassland/fast:
	$(MAKE) $(MAKESILENT) -f external/grassland/src/CMakeFiles/grassland.dir/build.make external/grassland/src/CMakeFiles/grassland.dir/build
.PHONY : grassland/fast

#=============================================================================
# Target rules for targets named grassland_file_lib

# Build rule for target.
grassland_file_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 grassland_file_lib
.PHONY : grassland_file_lib

# fast build rule for target.
grassland_file_lib/fast:
	$(MAKE) $(MAKESILENT) -f external/grassland/src/grassland/file/CMakeFiles/grassland_file_lib.dir/build.make external/grassland/src/grassland/file/CMakeFiles/grassland_file_lib.dir/build
.PHONY : grassland_file_lib/fast

#=============================================================================
# Target rules for targets named grassland_font_lib

# Build rule for target.
grassland_font_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 grassland_font_lib
.PHONY : grassland_font_lib

# fast build rule for target.
grassland_font_lib/fast:
	$(MAKE) $(MAKESILENT) -f external/grassland/src/grassland/font/CMakeFiles/grassland_font_lib.dir/build.make external/grassland/src/grassland/font/CMakeFiles/grassland_font_lib.dir/build
.PHONY : grassland_font_lib/fast

#=============================================================================
# Target rules for targets named grassland_imgui_lib

# Build rule for target.
grassland_imgui_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 grassland_imgui_lib
.PHONY : grassland_imgui_lib

# fast build rule for target.
grassland_imgui_lib/fast:
	$(MAKE) $(MAKESILENT) -f external/grassland/src/grassland/imgui/CMakeFiles/grassland_imgui_lib.dir/build.make external/grassland/src/grassland/imgui/CMakeFiles/grassland_imgui_lib.dir/build
.PHONY : grassland_imgui_lib/fast

#=============================================================================
# Target rules for targets named grassland_util_lib

# Build rule for target.
grassland_util_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 grassland_util_lib
.PHONY : grassland_util_lib

# fast build rule for target.
grassland_util_lib/fast:
	$(MAKE) $(MAKESILENT) -f external/grassland/src/grassland/util/CMakeFiles/grassland_util_lib.dir/build.make external/grassland/src/grassland/util/CMakeFiles/grassland_util_lib.dir/build
.PHONY : grassland_util_lib/fast

#=============================================================================
# Target rules for targets named grassland_vulkan_lib

# Build rule for target.
grassland_vulkan_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 grassland_vulkan_lib
.PHONY : grassland_vulkan_lib

# fast build rule for target.
grassland_vulkan_lib/fast:
	$(MAKE) $(MAKESILENT) -f external/grassland/src/grassland/vulkan/CMakeFiles/grassland_vulkan_lib.dir/build.make external/grassland/src/grassland/vulkan/CMakeFiles/grassland_vulkan_lib.dir/build
.PHONY : grassland_vulkan_lib/fast

#=============================================================================
# Target rules for targets named grassland_vulkan_lib_flattened_shaders

# Build rule for target.
grassland_vulkan_lib_flattened_shaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 grassland_vulkan_lib_flattened_shaders
.PHONY : grassland_vulkan_lib_flattened_shaders

# fast build rule for target.
grassland_vulkan_lib_flattened_shaders/fast:
	$(MAKE) $(MAKESILENT) -f external/grassland/src/grassland/vulkan/shaders/CMakeFiles/grassland_vulkan_lib_flattened_shaders.dir/build.make external/grassland/src/grassland/vulkan/shaders/CMakeFiles/grassland_vulkan_lib_flattened_shaders.dir/build
.PHONY : grassland_vulkan_lib_flattened_shaders/fast

#=============================================================================
# Target rules for targets named grassland_vulkan_lib_shader_files

# Build rule for target.
grassland_vulkan_lib_shader_files: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 grassland_vulkan_lib_shader_files
.PHONY : grassland_vulkan_lib_shader_files

# fast build rule for target.
grassland_vulkan_lib_shader_files/fast:
	$(MAKE) $(MAKESILENT) -f external/grassland/src/grassland/vulkan/shaders/CMakeFiles/grassland_vulkan_lib_shader_files.dir/build.make external/grassland/src/grassland/vulkan/shaders/CMakeFiles/grassland_vulkan_lib_shader_files.dir/build
.PHONY : grassland_vulkan_lib_shader_files/fast

#=============================================================================
# Target rules for targets named grassland_vulkan_legacy_lib

# Build rule for target.
grassland_vulkan_legacy_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 grassland_vulkan_legacy_lib
.PHONY : grassland_vulkan_legacy_lib

# fast build rule for target.
grassland_vulkan_legacy_lib/fast:
	$(MAKE) $(MAKESILENT) -f external/grassland/src/grassland/vulkan_legacy/CMakeFiles/grassland_vulkan_legacy_lib.dir/build.make external/grassland/src/grassland/vulkan_legacy/CMakeFiles/grassland_vulkan_legacy_lib.dir/build
.PHONY : grassland_vulkan_legacy_lib/fast

#=============================================================================
# Target rules for targets named battle_game

# Build rule for target.
battle_game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 battle_game
.PHONY : battle_game

# fast build rule for target.
battle_game/fast:
	$(MAKE) $(MAKESILENT) -f src/battle_game/CMakeFiles/battle_game.dir/build.make src/battle_game/CMakeFiles/battle_game.dir/build
.PHONY : battle_game/fast

#=============================================================================
# Target rules for targets named battle_game_app_lib

# Build rule for target.
battle_game_app_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 battle_game_app_lib
.PHONY : battle_game_app_lib

# fast build rule for target.
battle_game_app_lib/fast:
	$(MAKE) $(MAKESILENT) -f src/battle_game/app/CMakeFiles/battle_game_app_lib.dir/build.make src/battle_game/app/CMakeFiles/battle_game_app_lib.dir/build
.PHONY : battle_game_app_lib/fast

#=============================================================================
# Target rules for targets named battle_game_app_lib_flattened_shaders

# Build rule for target.
battle_game_app_lib_flattened_shaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 battle_game_app_lib_flattened_shaders
.PHONY : battle_game_app_lib_flattened_shaders

# fast build rule for target.
battle_game_app_lib_flattened_shaders/fast:
	$(MAKE) $(MAKESILENT) -f src/battle_game/app/CMakeFiles/battle_game_app_lib_flattened_shaders.dir/build.make src/battle_game/app/CMakeFiles/battle_game_app_lib_flattened_shaders.dir/build
.PHONY : battle_game_app_lib_flattened_shaders/fast

#=============================================================================
# Target rules for targets named battle_game_app_lib_shader_files

# Build rule for target.
battle_game_app_lib_shader_files: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 battle_game_app_lib_shader_files
.PHONY : battle_game_app_lib_shader_files

# fast build rule for target.
battle_game_app_lib_shader_files/fast:
	$(MAKE) $(MAKESILENT) -f src/battle_game/app/CMakeFiles/battle_game_app_lib_shader_files.dir/build.make src/battle_game/app/CMakeFiles/battle_game_app_lib_shader_files.dir/build
.PHONY : battle_game_app_lib_shader_files/fast

#=============================================================================
# Target rules for targets named battle_game_core_lib

# Build rule for target.
battle_game_core_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 battle_game_core_lib
.PHONY : battle_game_core_lib

# fast build rule for target.
battle_game_core_lib/fast:
	$(MAKE) $(MAKESILENT) -f src/battle_game/core/CMakeFiles/battle_game_core_lib.dir/build.make src/battle_game/core/CMakeFiles/battle_game_core_lib.dir/build
.PHONY : battle_game_core_lib/fast

#=============================================================================
# Target rules for targets named battle_game_graphics_lib

# Build rule for target.
battle_game_graphics_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 battle_game_graphics_lib
.PHONY : battle_game_graphics_lib

# fast build rule for target.
battle_game_graphics_lib/fast:
	$(MAKE) $(MAKESILENT) -f src/battle_game/graphics/CMakeFiles/battle_game_graphics_lib.dir/build.make src/battle_game/graphics/CMakeFiles/battle_game_graphics_lib.dir/build
.PHONY : battle_game_graphics_lib/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... battle_game_app_lib_flattened_shaders"
	@echo "... battle_game_app_lib_shader_files"
	@echo "... grassland_vulkan_lib_flattened_shaders"
	@echo "... grassland_vulkan_lib_shader_files"
	@echo "... battle_game"
	@echo "... battle_game_app_lib"
	@echo "... battle_game_core_lib"
	@echo "... battle_game_graphics_lib"
	@echo "... grassland"
	@echo "... grassland_file_lib"
	@echo "... grassland_font_lib"
	@echo "... grassland_imgui_lib"
	@echo "... grassland_util_lib"
	@echo "... grassland_vulkan_legacy_lib"
	@echo "... grassland_vulkan_lib"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

